version: '3'
services:
  app:
    image: ghcr.io/opsilab/roadsteamer-cop-suite:v0.1
    volumes:
      - .:/code
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      - PORT=3000
      - DATABASE_HOST=192.168.1.37
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=D@niele991
    ports:
      - 3000:3000
    links:
      - pg
    command: /code/init.sh
  pg:
    image: postgres
    ports: 
     - 5000:5432 
    volumes:
         - pg-data:/var/lib/postgresql/data
    environment:
     - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
